apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdm-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: sdm-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: sdm-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sdm-role
subjects:
  - kind: ServiceAccount
    name: sdm-serviceaccount
